### ISSUE TITLE
Deal with lots of little things in the form UI

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#139]

**Comment by mapsam** [comment]
Here is a list of the issues _relatively related_ to UI in the forms. @bengolder there is a lot here! I think you've started working on bunch of them in #133 - let me know where I can help out.

**Non-technical issues to bring to service providers**
- [ ] #101, User not entirely sure if they can leave fields blank or not
- [ ] #100, What is the best way to handle gender options?
- [ ] #113, Difference between race and ethnicity fields is confusing

**General**
- [ ] #123, Comma in number field leaves cryptic error
- [ ] #126, Dollar fields should be prefixed with dollar sign to prevent user from entering the symbol

**Patient Details**
- [ ] #118, Dynamically update "patient" row in household members table when patient name is updated
- [ ] #117, Add FPL percentage calculation to patient details page?
- [ ] #114, Users aren't sure what "personal documents" means
- [ ] #111, Convert dropdowns to radio or checkbox buttons
- [x] #110, Implement conditional field display
- [x] #103, When you say you "do not have insurance" it still asks "what type"

**Prescreening**
- [ ] #97, Make monthly income more explicit and do some calculations for the user/patient.
- [ ] #98, Medicaid question is not as simple as yes/no

**Comment by bengolder** [comment]
@mapsam Thanks for pulling all these together.

**Comment by bengolder** [comment]
Regarding form validation for #123, #126, and #133, I did some planning regarding how to implement validation. In terms of displaying help text and error messages, this also relates to #83 

For which inputs should we be concerned about invalid inputs?
- phone number inputs
- dates
- emails
- zip codes
- SSN inputs
- dollar amounts
- name and date of birth (should not be empty)

Can they be prevented with help text? - Most could use examples
Can these be prevented with parsing? - yes, most can
Can they be resolved with error messages? - yes, all could be probably resolved by showing an error message.

When should validation occur and messages be displayed? 
- only after parsing takes place
- When the input loses focus
- When the page is loaded after a form submittal

Where should messages be displayed?
- in some of these cases, examples should be displayed in the help text, and those examples should simply be re-emphasized. No additional pop up should be displayed.
- Visually, they should be encapsulated flags pointing at labels, as discussed in this
  answer: http://ux.stackexchange.com/a/26176/4412
- Ideally, they should be inserted into the HTML (before the field) without obscuring other elements, and should not disturb the scroll position.
- they should also be placed at the beginning of the form (again, this may cause an issue with scroll position)

**Comment by esmithayer** [comment]
Closing this since it's separated out into #167 (form validation), #168 (patient details UI), and #169 (prescreening UI).
