### ISSUE TITLE
Patient details UI/copy changes

### ISSUE THREAD

**Issue by esmithayer** [codeforamerica/rva-screening#168]
- [ ] #101, User not entirely sure if they can leave fields blank or not
- [ ] #100, What is the best way to handle gender options?
- [ ] #113, Difference between race and ethnicity fields is confusing
- [ ] #114, Users aren't sure what "personal documents" means
- [ ] #111, Convert dropdowns to radio or checkbox buttons
- [ ] #83, Set up "tooltips" on hover for more explanation
- [x] Add some sort of save reminder if patient clicks away without saving

**Comment by mapsam** [comment]
**Gender & Transgender**

We've heard from our most recent (October) trip that the gender/transgender separation can be offensive and combining them into the same dropdown response would make more sense, as long as we can provide a question that can answer for "biological sex at birth".

**Race**

While testing at the resource centers, people said that only allowing _one_ selection in the dropdown for race can be limiting. We can turn these into checkboxes. Thoughts? This also relates to #111
