### ISSUE TITLE
Prescreening UI/copy changes

### ISSUE THREAD

**Issue by esmithayer** [codeforamerica/rva-screening#169]
- [x] #97, Make monthly income more explicit and do some calculations for the user/patient.
- [x] #98, Medicaid question is not as simple as yes/no
- [x] #119 Prescreen service selection unclear
- [x] #111 Convert dropdowns to radio or checkbox buttons
- [x] #101 Users not sure if they can leave fields blank or not
