### ISSUE TITLE
Preparation for next visit - updates & fixes

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#183]
Just a jumble of small tasks after merging changes from #179
- [x] update filter buttons to be mobile friendly, taken from #179 
- [x] remove "prescreener" button from login page (when logged out)
- [x] add mockup of inline-edits (tooltips? #83) to patient details page (will expand upon if time allows!)
- [x] ~~how can we show Clinic-specific questions right now in our current status (not as a permanent fix, but as a way to get the info down before our visit)? @esmithayer suggested having checkboxes on the sidebar of the patient details page that can toggle clinic's questions. Seems like a potential use for `.filter` elements again.~~ answered by using `.filter` buttons again and showing/hiding questions with new classes added in #185 
- [x] add clinic-specific questions
- [x] add questions to javascript for conditional display [in this file](https://github.com/codeforamerica/rva-screening/blob/master/front/js/question_dependencies.js)
- [x] cleanup (spacing, colors, text hierarchy, titles)
- [x] find any new strings that haven't been translated and add to translation document
- [x] ~~mockups of patient status listings/notifications~~ saving for post trip
- [x] sample email to a screener after referring patient
- [x] We need the HTML of the forms to look [more like this](https://github.com/codeforamerica/rva-screening-ui-prototypes/blob/master/app/templates/patient_details.html#L92-L101). Going to edit WTForm templates.
- [x] style mobile menu button more elegantly
- [x] update prescreener information (#144, #169)
- [x] add classes & change HTML to address new CSS changes
- [x] adjust the width of various fields, particularly year & month inputs.
- [x] move filter-related javascript into filter.js
- [x] add "saved successfully" to the patient details page
- [x] glyphicons :point_right: font-awesome on the patient details page
- [x] update buttons on patient details page
- [x] write CSS for radio buttons
- [x] remove "prescreen this patient" button
- [x] add some extra space to top of patient page
- [x] ~~create new macro for multiforms~~
- [x] ~~update many-to-one field deletions that don't have [state set as Virginia](https://github.com/codeforamerica/rva-screening/blob/master/app/views.py#L139)~~ opened separate issue #223 
- [x] update button styles on patient referral page once they have been sent
- [x] add a footer to the app
- [x] RVA logo on nav

**Comment by mapsam** [comment]
Added super basic tooltips for in-context edit history. This should be fleshed out much more, with multiple lines and lists (probably move into javascript) - but for now it's just CSS.

<img width="899" alt="screen shot 2015-07-27 at 11 33 50 am" src="https://cloud.githubusercontent.com/assets/1943001/8914344/90f1751c-3453-11e5-9c2a-79f74466056b.png">

**Comment by mapsam** [comment]
Have some super preliminary clinic-specific filters built into the sidebar. Going to pause until the questions are added in by @bengolder so we can filter with the proper classes.

![rva-screener-servicespecificquestions](https://cloud.githubusercontent.com/assets/1943001/8920569/8bda25b6-347f-11e5-9ebb-a761790be541.gif)

**Comment by mapsam** [comment]
Added some sidebar information to the patient profile, including some tooltips

<img width="326" alt="screen shot 2015-07-28 at 2 56 30 pm" src="https://cloud.githubusercontent.com/assets/1943001/8945031/dec6db84-3538-11e5-87d4-d62827b7b5f1.png">

**Comment by mapsam** [comment]
Backend alerts are styled for error and success:

<img width="841" alt="screen shot 2015-07-28 at 4 24 18 pm" src="https://cloud.githubusercontent.com/assets/1943001/8946468/492c6050-3545-11e5-9b92-eff856321e46.png">
<img width="846" alt="screen shot 2015-07-28 at 4 24 43 pm" src="https://cloud.githubusercontent.com/assets/1943001/8946467/492a5c9c-3545-11e5-8d37-13b6eb21169f.png">

**Comment by mapsam** [comment]
Some styles for patient screening history:

<img width="814" alt="screen shot 2015-07-28 at 9 22 36 pm" src="https://cloud.githubusercontent.com/assets/1943001/8949928/01cc5db2-356f-11e5-953e-4d1f7e349de2.png">

**Comment by mapsam** [comment]
Closing this issue - leftovers were hanging cleanup issues except for #223
